VERILOG = ../src/sms.v ../src/ram.v ../src/vram.v ../src/rom.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/video.v ../src/hdmi.v \
	  ../src/sn76489.v ../src/tone_generator.v ../src/sigmadelta.v\
	  ../src/lattice/ecp5pll.sv \
	  ../src/sdram.v \
          ../src/spi_display/lcd_video.v \
          ../src/spi_display/hex_decoder_v.v \
	  ../src/serial_loader.v

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

